# Generated by Django 5.1.3 on 2025-04-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=255)),
                ('predicted_severity', models.CharField(choices=[('low', 'Low (Normal Traffic)'), ('medium', 'Medium (Congestion)'), ('high', 'High (Severe Delay)')], max_length=20)),
                ('predicted_duration_min', models.PositiveIntegerField(help_text='Predicted ETA (in minutes) including delay')),
                ('usual_duration_min', models.PositiveIntegerField(help_text='Base travel time without congestion')),
                ('confidence_score', models.FloatField(blank=True, help_text='Model confidence (0.0–1.0)', null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_at', models.DateTimeField(blank=True, help_text='When this prediction becomes stale', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = Outdated prediction')),
            ],
            options={
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['route_id'], name='congestion__route_i_6e5aea_idx'), models.Index(fields=['-predicted_at'], name='congestion__predict_19b6f8_idx')],
            },
        ),
    ]
